// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeTd8Psao4Y9akEM6aWK4C1unR1oYSS4g',
    appId: '1:990792833302:web:fc998fcb791968c2bd9837',
    messagingSenderId: '990792833302',
    projectId: 'onlinefish-b13e1',
    authDomain: 'onlinefish-b13e1.firebaseapp.com',
    storageBucket: 'onlinefish-b13e1.firebasestorage.app',
    measurementId: 'G-XY2CGDH0NW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx71MR4JZ6ytOclvUqT4KQfjqwPBA9vb8',
    appId: '1:990792833302:android:632d144f61246c99bd9837',
    messagingSenderId: '990792833302',
    projectId: 'onlinefish-b13e1',
    storageBucket: 'onlinefish-b13e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeTd8Psao4Y9akEM6aWK4C1unR1oYSS4g',
    appId: '1:990792833302:web:c0096f5be97fa9e3bd9837',
    messagingSenderId: '990792833302',
    projectId: 'onlinefish-b13e1',
    authDomain: 'onlinefish-b13e1.firebaseapp.com',
    storageBucket: 'onlinefish-b13e1.firebasestorage.app',
    measurementId: 'G-JH2KWLDD47',
  );
}
